import { Project, Product } from '@/types/types';

// モックプロジェクトデータ - 3年生の食べ物企画のみ
export const mockProjects: Project[] = [
    {
        id: 1,
        name: 'カフェ「星空テラス」',
        description:
            '星をテーマにしたおしゃれなカフェ。手作りスイーツとドリンクが自慢です。天体観測をイメージした幻想的な装飾の中で、特製メニューをお楽しみください。',
        thumbnail: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop',
        className: 'A',
        academicYear: 2024,
        createdById: 'user1',
    },
    {
        id: 2,
        name: '和食レストラン「桜庵」',
        description:
            '本格的な和食を楽しめる落ち着いた雰囲気のレストラン。手打ちうどんや季節の天ぷらなど、こだわりの和食メニューを提供します。',
        thumbnail: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&h=600&fit=crop',
        className: 'B',
        academicYear: 2024,
        createdById: 'user2',
    },
    {
        id: 3,
        name: 'ピザ&パスタ「イタリア広場」',
        description:
            '本格イタリアンが楽しめる陽気な雰囲気のお店。手作りピザと自慢のパスタで、イタリアの味をお届けします。',
        thumbnail: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=600&fit=crop',
        className: 'C',
        academicYear: 2024,
        createdById: 'user3',
    },
    {
        id: 4,
        name: 'スイーツパラダイス「甘味処」',
        description:
            '手作りスイーツ専門店。季節のフルーツを使ったケーキやパフェ、伝統的な和菓子まで、甘いもの好きにはたまらないお店です。',
        thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop',
        className: 'D',
        academicYear: 2024,
        createdById: 'user4',
    },
    {
        id: 5,
        name: '韓国料理「ソウルキッチン」',
        description:
            '本場の韓国料理が味わえる人気店。チーズダッカルビやキンパなど、話題の韓国グルメを手軽に楽しめます。',
        thumbnail: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&h=600&fit=crop',
        className: 'E',
        academicYear: 2024,
        createdById: 'user5',
    },
    {
        id: 6,
        name: 'ドリンクバー「リフレッシュステーション」',
        description:
            'オリジナルドリンクとフレッシュジュースの専門店。手作りタピオカドリンクや季節限定フレーバーが人気です。',
        thumbnail: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&h=600&fit=crop',
        className: 'F',
        academicYear: 2024,
        createdById: 'user6',
    },
];

// モック商品データ - 3年生の食べ物企画の商品
export const mockProducts: Product[] = [
    // 3-A カフェ「星空テラス」の商品
    {
        id: 1,
        name: 'スターライトケーキ',
        description:
            '星形のチョコレートケーキ。夜空をイメージした美しいデコレーションが特徴的で、見た目も味も最高です！',
        price: 400,
        thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&h=400&fit=crop',
            'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=400&fit=crop',
        ],
        isSoldOut: false,
        sales: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user1',
        projectId: 1,
        calories: 320,
        protein: 6,
        fat: 18,
        carbohydrate: 35,
        sodium: 150,
        hasEbi: false,
        hasKani: false,
        hasKurumi: true,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 2,
        name: 'ギャラクシーラテ',
        description: '美しいラテアートが特徴の特製コーヒー。宇宙をイメージしたアートで、インスタ映え間違いなし！',
        price: 250,
        thumbnail: 'https://images.unsplash.com/photo-1545665225-b23b99e4d45e?w=600&h=400&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1545665225-b23b99e4d45e?w=600&h=400&fit=crop',
            'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop',
        ],
        isSoldOut: false,
        sales: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user1',
        projectId: 1,
        calories: 120,
        protein: 8,
        fat: 5,
        carbohydrate: 15,
        sodium: 50,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: false,
        hasSoba: false,
        hasTamago: false,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 3,
        name: '流れ星パフェ',
        description:
            '色とりどりのフルーツとアイスクリームで作った豪華パフェ。食べるのがもったいないほど美しい見た目です。',
        price: 450,
        thumbnail: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 180,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user1',
        projectId: 1,
        calories: 380,
        protein: 5,
        fat: 12,
        carbohydrate: 65,
        sodium: 80,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: true,
        hasRakkasei: false,
    },

    // 3-B 和食レストラン「桜庵」の商品
    {
        id: 4,
        name: '手打ちうどん',
        description: 'コシのある手打ちうどんに、秘伝のだしが自慢の一品。温かいうどんで心も体も温まります。',
        price: 350,
        thumbnail: 'https://images.unsplash.com/photo-1618841557871-b4664fbf0cb3?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1618841557871-b4664fbf0cb3?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 220,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user2',
        projectId: 2,
        calories: 280,
        protein: 12,
        fat: 2,
        carbohydrate: 58,
        sodium: 800,
        hasEbi: true,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: false,
        hasRakkasei: false,
    },
    {
        id: 5,
        name: '季節の天ぷら定食',
        description: '新鮮な野菜と海老を使った天ぷら定食。サクサクの衣と素材の旨味をお楽しみください。',
        price: 500,
        thumbnail: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 160,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user2',
        projectId: 2,
        calories: 480,
        protein: 18,
        fat: 15,
        carbohydrate: 65,
        sodium: 900,
        hasEbi: true,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: false,
        hasRakkasei: false,
    },

    // 3-C ピザ&パスタ「イタリア広場」の商品
    {
        id: 6,
        name: 'マルゲリータピザ',
        description:
            'シンプルながら本格的なマルゲリータピザ。トマトソース、モッツァレラ、バジルの絶妙なハーモニーをお楽しみください。',
        price: 600,
        thumbnail: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user3',
        projectId: 3,
        calories: 520,
        protein: 20,
        fat: 22,
        carbohydrate: 55,
        sodium: 1100,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: false,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 7,
        name: 'カルボナーラパスタ',
        description: 'クリーミーで濃厚なカルボナーラ。チーズと卵の絶妙なバランスが自慢の一品です。',
        price: 550,
        thumbnail: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 240,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user3',
        projectId: 3,
        calories: 450,
        protein: 18,
        fat: 20,
        carbohydrate: 48,
        sodium: 950,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: true,
        hasRakkasei: false,
    },

    // 3-D スイーツパラダイス「甘味処」の商品
    {
        id: 8,
        name: '季節のフルーツタルト',
        description:
            '新鮮な季節のフルーツをたっぷり使った贅沢なタルト。サクサクのタルト生地とカスタードクリームが絶品です。',
        price: 380,
        thumbnail: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 190,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user4',
        projectId: 4,
        calories: 280,
        protein: 4,
        fat: 12,
        carbohydrate: 42,
        sodium: 120,
        hasEbi: false,
        hasKani: false,
        hasKurumi: true,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: true,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 9,
        name: '抹茶白玉ぜんざい',
        description: '上品な甘さの抹茶と、もちもちの白玉が絶妙にマッチした和スイーツ。心がほっこりする味わいです。',
        price: 320,
        thumbnail: 'https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1582716401301-b2407dc7563d?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 140,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user4',
        projectId: 4,
        calories: 180,
        protein: 6,
        fat: 1,
        carbohydrate: 40,
        sodium: 80,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: false,
        hasSoba: false,
        hasTamago: false,
        hasMilk: false,
        hasRakkasei: false,
    },

    // 3-E 韓国料理「ソウルキッチン」の商品
    {
        id: 10,
        name: 'チーズダッカルビ',
        description:
            'とろ〜りチーズと甘辛い鶏肉の絶妙なコンビネーション。韓国で大人気のグルメを本格的な味で再現しました。',
        price: 650,
        thumbnail: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 280,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user5',
        projectId: 5,
        calories: 580,
        protein: 32,
        fat: 28,
        carbohydrate: 45,
        sodium: 1200,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: true,
        hasSoba: false,
        hasTamago: false,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 11,
        name: 'キンパ（韓国のり巻き）',
        description: '具材たっぷりの韓国のり巻き。牛肉、野菜、卵焼きなどが入った栄養満点の一品です。',
        price: 400,
        thumbnail: 'https://images.unsplash.com/photo-1553978297-833d09932d29?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1553978297-833d09932d29?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 210,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user5',
        projectId: 5,
        calories: 350,
        protein: 15,
        fat: 8,
        carbohydrate: 55,
        sodium: 800,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: false,
        hasSoba: false,
        hasTamago: true,
        hasMilk: false,
        hasRakkasei: false,
    },

    // 3-F ドリンクバー「リフレッシュステーション」の商品
    {
        id: 12,
        name: 'タピオカミルクティー',
        description: 'もちもちタピオカと香り高いミルクティーの定番コンビ。手作りタピオカの食感をお楽しみください。',
        price: 300,
        thumbnail: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 320,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user6',
        projectId: 6,
        calories: 220,
        protein: 4,
        fat: 3,
        carbohydrate: 48,
        sodium: 60,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: false,
        hasSoba: false,
        hasTamago: false,
        hasMilk: true,
        hasRakkasei: false,
    },
    {
        id: 13,
        name: 'フレッシュマンゴースムージー',
        description: '完熟マンゴーをたっぷり使ったトロピカルスムージー。暑い日にぴったりのさっぱりとした味わいです。',
        price: 350,
        thumbnail: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&h=400&fit=crop',
        images: ['https://images.unsplash.com/photo-1546173159-315724a31696?w=600&h=400&fit=crop'],
        isSoldOut: false,
        sales: 180,
        createdAt: new Date(),
        updatedAt: new Date(),
        academicYear: 2024,
        createdById: 'user6',
        projectId: 6,
        calories: 150,
        protein: 2,
        fat: 0,
        carbohydrate: 38,
        sodium: 10,
        hasEbi: false,
        hasKani: false,
        hasKurumi: false,
        hasKomugi: false,
        hasSoba: false,
        hasTamago: false,
        hasMilk: false,
        hasRakkasei: false,
    },
];
